config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'
  resources :bookings, only: [:show, :create, :new]
  resources :flights

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departures, class_name: 'Flight', foreign_key: 'start'
  has_many :arrivals, class_name: 'Flight', foreign_key: 'end'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :passengers
  has_one :flight, foreign_key: :id, primary_key: :flight_id
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  has_one :departure, class_name: 'Airport', primary_key: :start, foreign_key: :id
  has_one :arrival, class_name: 'Airport', primary_key: :end, foreign_key: :id
  has_many :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  has_one :flight, through: :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find_by(id: params[:flight])
    @passenger_num = params[:passengers]
    @booking = Booking.new
    @passenger_num.to_i.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      redirect_to @booking
      @booking.passengers.each do |p|
        PassengerMailer.with(user: p).thanks_email.deliver_later
      end
    else
      render 'new'
    end

  end

  def show
    @booking = Booking.find_by(id: params[:id])
  end

  private

    def booking_params
      params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
    end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airports = Airport.all.map { |f| ["#{f.name} (#{f.code})", f.id] }
    @dates_distinct = Flight.select(:date).distinct.order('date ASC')
    @dates = @dates_distinct.all.map { |f| [f.date.strftime('%m/%d/%y'), f.date] }
    if params[:search]
      @flights = Flight.where(
        start: params[:search][:start], 
        end: params[:search][:end], 
        date: date_range(params[:search][:date])
        ).limit(30)
    end

  end

  def fill(param)
    if params[:search]
      params[:search][param]
    else
      params[:search]
    end
  end

  def date_range(date)
    Date.parse("#{date}").beginning_of_day..Date.parse("#{date}").end_of_day
  end

  private

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<div>
	<h1>Enter passenger information</h1>
	<p>Flight information:</p>
	<p>Flight number: <%= @flight.id %> Date: <%= @flight.date %> </p>
	<p>Departing: <%= @flight.departure.name %></p>
	<p>Arriving: <%= @flight.arrival.name %></p>
	<div>
		<%= form_with model: @booking, url: bookings_path, method: :post, local:true do |f| %>
		<ul>
			<%= f.fields_for :passengers do |form| %>
				<li>
					<%= form.label :passenger %><br>
					<%= form.label :name %>
					<%= form.text_field :name %>

					<%= form.label :email %>
					<%= form.email_field :email %>
				</li>
				<br>
				<% end %>
		</ul>
			<%= f.hidden_field :flight_id, value: @flight.id %>
			<%= f.submit 'Create booking' %>
		<% end %>
	</div>
</div>

app/views/bookings/show.html.erb
<div>
	<h1>Your booking</h1>
	<div>
		<p>Booking number: <%= @booking.id %></p>
		<h3>Flight information</h3>
		<p>Flight number: <%= @booking.flight.id %></p>
		<p>Departing: <%= @booking.flight.departure.name %> at <%= @booking.flight.date.strftime("%a, %D, %r") %> </p>
		<p>Arriving: <%= @booking.flight.arrival.name %> at <%= (@booking.flight.date + @booking.flight.duration).strftime("%a, %D, %r") %></p>
		<h3>Passenger information</h3>
		<ul>
			<% @booking.passengers.each do |p| %>
				<li><%= p.name %> </li><br>
			<% end %>
		</ul>
	</div>
</div>

app/views/flights/index.html.erb
<h1>Find your flight!</h1>

<div>
	<%= form_with scope: :search, url: flights_path, method: :get, local:true do |f| %>
		<%= f.label :from %>
		<%= f.select(:start, @airports, selected: (params[:search][:start] if params[:search])) %>

		<%= f.label :to %>
		<%= f.select(:end, @airports, selected: (params[:search][:end] if params[:search])) %>

		<%= f.label :passengers %>
		<%= f.select(:passengers, [1, 2, 3, 4], selected: (params[:search][:passengers] if params[:search])) %>

		<%= f.label :date %>
		<%= f.select(:date, @dates, selected: (params[:search][:date] if params[:search])) %>

		<%= f.submit 'Search' %>
	<% end %>
</div>

<div>
	<% if @flights.nil? %>
		<p>Search for a flight!</p>
	<% else %>
		<% if @flights.any? %>
			<%= form_with url: new_booking_path, method: :get, local: true do |f| %>
				<% @flights.each do |flight| %>
					<li><%= flight.id %>, <%= flight.departure.name %>, <%= flight.arrival.name %>, <%= flight.duration.to_i/3600 %> hours <%= radio_button_tag :flight, flight.id %> </li>
				<% end %>
				<%= hidden_field_tag :passengers, params[:search][:passengers] if params[:search] %>
				<%= f.submit 'Choose' %>
			<% end %>
		<% else %>
			<p>There are no flights for the selected airports</p>
		<% end %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>